databases:
  - name: essencedb
    plan: free
    databaseName: essence
    user: essence

services:
  - type: web
    plan: free
    name: essence
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn project.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: essencedb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DJANGO_SETTINGS_MODULE
        value: project.settings.production