# Generated by Django 5.0.3 on 2024-03-29 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_brand_name_alter_gender_name_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'gender')},
        ),
    ]
