# Generated by Django 5.0.3 on 2024-04-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='image',
            field=models.ImageField(default='', upload_to='product_types'),
            preserve_default=False,
        ),
    ]
