# Generated by Django 5.0.3 on 2024-04-01 20:47

import apps.utils.upload
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_producttype_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='image',
            field=models.ImageField(upload_to=functools.partial(apps.utils.upload.unique_file_name_generator, *(), **{'base_path': 'product-types'})),
        ),
    ]
