# Generated by Django 5.0.3 on 2024-04-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_gender_name_alter_producttype_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='name',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Kid', 'Kid')], default='Men', max_length=10, unique=True),
        ),
    ]
