# Generated by Django 5.0.3 on 2024-04-01 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_gender_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='name',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('kid', 'Kid')], default='men', max_length=10, unique=True),
        ),
    ]
