# Generated by Django 5.0.3 on 2024-04-02 10:19

import apps.utils.upload
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_product_brand_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(default='', upload_to=functools.partial(apps.utils.upload.unique_file_name_generator, *('product-images',), **{})),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='secondary_image',
            field=models.ImageField(blank=True, null=True, upload_to=functools.partial(apps.utils.upload.unique_file_name_generator, *('product-images',), **{})),
        ),
    ]
