# Generated by Django 5.0.3 on 2024-04-04 12:58

import apps.utils.upload
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_remove_product_secondary_image_product_hover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='hover_image',
            field=models.ImageField(blank=True, help_text='Image of product when hovered - ideal resolution of 1000x1364', null=True, upload_to=functools.partial(apps.utils.upload.unique_file_name_generator, *(), **{'base_path': 'product-images'})),
        ),
        migrations.AlterField(
            model_name='product',
            name='secondary_single_view_image',
            field=models.ImageField(default='', help_text='Image of product in single product view - ideal resolution of 1000x972', upload_to=functools.partial(apps.utils.upload.unique_file_name_generator, *(), **{'base_path': 'product-images'})),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='single_view_image',
            field=models.ImageField(help_text='Image of product in single product view - ideal resolution of 1000x972', upload_to=functools.partial(apps.utils.upload.unique_file_name_generator, *(), **{'base_path': 'product-images'})),
        ),
    ]
